### ISSUE TITLE
Src.main not created during set up process

### ISSUE THREAD

**Issue by nielsenz** [modal-labs/devlooper#1]
Hello,

Potentially user error, but while I was going through the startup process, src.main was never created. This led to a module not found error error when I tried to run your example command, i.e. modal run src.main --prompt="a simple 2D graphics library" --template="rust", with no module named "src" found. If you could help it would be greatly appreciated!

**Comment by aksh-at** [comment]
Hey @nielsenz, are you running it from the root directory of the repo? I.e. if you `ls` from your current directory, it should have the folder `src` present. Let me know if you're still running into issues.

**Comment by nielsenz** [comment]
All good! Didn't realize I had to clone the repo - it's now working great for me! Thanks again for the quick response
